<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17595" started-at="2021-02-22T11:03:32Z" finished-at="2021-02-22T11:03:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17595" started-at="2021-02-22T11:03:32Z" finished-at="2021-02-22T11:03:50Z">
      <class name="Testscripts.Valid_login">
        <test-method status="PASS" signature="openAppln()[pri:0, instance:Testscripts.Valid_login@4b9e13df]" name="openAppln" is-config="true" duration-ms="11198" started-at="2021-02-22T16:33:32Z" finished-at="2021-02-22T16:33:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method status="FAIL" signature="login()[pri:0, instance:Testscripts.Valid_login@4b9e13df]" name="login" duration-ms="3356" started-at="2021-02-22T16:33:44Z" finished-at="2021-02-22T16:33:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Testscripts.Valid_login.login(Valid_login.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="closeAppln(org.testng.ITestResult)[pri:0, instance:Testscripts.Valid_login@4b9e13df]" name="closeAppln" is-config="true" duration-ms="3014" started-at="2021-02-22T16:33:47Z" finished-at="2021-02-22T16:33:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=Valid_login.login()[pri:0, instance:Testscripts.Valid_login@4b9e13df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- Testscripts.Valid_login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
